apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
     metadata:
       name: redis-pod
       labels:
         name: redis-pod
         apps: demo-voting-app
     spec:
         containers:
           - name: redis
             image: redis
             ports:
             - containerPort: 6379


